POST http://localhost:8080/api/v1/business/signup
Content-Type: application/json

{
		"businessName":"사업자3",
		"businessEmail":"business1@email.com",
	     "businessPwd":"testT!123",
		"businessNum":"133-12-12345"
}

### 로그인
POST http://localhost:8080/login/business
Content-Type: application/json

{
  "email" : "business4@gmail.com",
  "password" : "Test1234!"

}
### 사업자 구독

GET http://localhost:8080/api/subscribe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoiYnVzaW5lc3M0QGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0JVU0lORVNTIiwiaWF0IjoxNzMzNjUxMDc1LCJleHAiOjE3MzM2NTE5NzV9.cU4C3qoL9UIpV2Z5JGqRViNvcm9yzd7cyTnduFOgWrc
Accept: text/event-stream

### 멤버 구독

GET http://localhost:8080/api/subscribe/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoibWVtYmVyMUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzMzNjUxMTgyLCJleHAiOjE3MzM2NTIwODJ9.T-zXWwcPANZtdWDAcqbQAYBHuccCP-R40nJncRWo91E
Accept: text/event-stream

### 예약등록

POST http://localhost:8080/api/v1/reservations/9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoibWVtYmVyMUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzMzNjUxMTgyLCJleHAiOjE3MzM2NTIwODJ9.T-zXWwcPANZtdWDAcqbQAYBHuccCP-R40nJncRWo91E

{
  "reservationName": "홍길동",
  "reservationPhoneNumber": "010-0000-0000",
  "capacity" : 4,
  "price" : 12000,
  "startTime": "2024-12-02T10:00:00",
  "endTime": "2024-12-02T11:59:00"
}
### 결제
POST http://localhost:8080//api/v1/payments/toss?reservationId=21
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoibWVtYmVyMUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzMzNjUxMTgyLCJleHAiOjE3MzM2NTIwODJ9.T-zXWwcPANZtdWDAcqbQAYBHuccCP-R40nJncRWo91E

{
  "orderId": "string",
  "orderName": "ABC 스터디룸 ROOM A 예약",
  "totalAmount": 12000,
  "memberName": "홍길동12",
  "memberPhoneNum": "010-0000-0000",
  "tossPaymentMethod": "CARD"
}

### 결제 성공
POST http://localhost:8080//api/v1/payments/toss/success?reservationId=24
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoiZXh0cmExQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJpYXQiOjE3MzM2NDMwNTgsImV4cCI6MTczMzY0Mzk1OH0.D85pBlmy5aErPgtFJD3Ujm0MTmX7TU5yOhNdFjTLdHw

{
  "orderId": "string",
  "orderName": "ABC 스터디룸 ROOM A 예약",
  "totalAmount": 12000,
  "memberName": "홍길동12",
  "memberPhoneNum": "010-0000-0000",
  "tossPaymentMethod": "CARD"
}
### 사업자 알람조회
GET  http://localhost:8080/api/v1/sub/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoiYnVzaW5lc3M1QGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0JVU0lORVNTIiwiaWF0IjoxNzMzNjUwMDc4LCJleHAiOjE3MzM2NTA5Nzh9.QtMHTLk4PPX6XnXwwWpw4lOJfGuKYEbA8ZIEu6MMs-4


### 결제 알람조회
GET  http://localhost:8080/api/v1/subReservation/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoiYnVzaW5lc3M1QGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0JVU0lORVNTIiwiaWF0IjoxNzMzNjUwMDc4LCJleHAiOjE3MzM2NTA5Nzh9.QtMHTLk4PPX6XnXwwWpw4lOJfGuKYEbA8ZIEu6MMs-4

### 사용자 알람조회
GET  http://localhost:8080/api/v1/subReservation/memberlist
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoibWVtYmVyMUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzMzNjUxMTgyLCJleHAiOjE3MzM2NTIwODJ9.T-zXWwcPANZtdWDAcqbQAYBHuccCP-R40nJncRWo91E


### 리뷰등록
POST http://localhost:8080/api/v1/review/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoiamFuZWRvZUBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzMzNjQ4MjQ0LCJleHAiOjE3MzM2NDkxNDR9.9-NrE4pj360Tf1j0Qf6JDaKX86553xl6UcyfNbbpOPI

{
    "reservationId" : 10,
    "workPlaceName" : "ENI스터디룸",
    "reviewContent": "좋습니다",
    "reviewRating" : 4
 }
### 멤버 회원가입
POST http://localhost:8080/api/v1/member/signup
Content-Type: application/json

{
    "nickName" : "테스트",
    "phoneNumber": "010-3333-2222",
    "sex" : "MALE",
    "email" : "123@aa.com",
    "pwd" : "Tpgur8597!!",
    "birthDay" : "2024-01-01"
}
### 멤버 로그인
POST http://localhost:8080/login/member
Content-Type: application/json

{

  "email" : "member1@gmail.com",
  "password" : "Test1234!"

}

### 예약 등록
POST http://localhost:8080/api/v1/reservations/12
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoibWVtYmVyNUBtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJpYXQiOjE3MzMzMTkxOTgsImV4cCI6MTczMzMyMDA5OH0.HpIkdS7MeuKbSRwPWrTGPm3CAMrd0ZhZdiH2NRVxI7M

{
  "reservationName": "홍길동",
  "reservationPhoneNumber": "010-0000-0000",
  "capacity" : 4,
  "price" : 12000,
  "startTime": "2024-12-03T13:00:00",
  "endTime": "2024-12-03T14:59:00"
}