POST http://localhost:8080/api/v1/business/signup
Content-Type: application/json

{
		"businessName":"사업자3",
		"businessEmail":"business1@email.com",
	     "businessPwd":"testT!123",
		"businessNum":"133-12-12345"
}

### 로그인
POST http://localhost:8080/login/business
Content-Type: application/json

{
  "email" : "business1@gmail.com",
  "password" : "Test1234!"

}
### 사업자 구독

GET http://localhost:8080/api/subscribe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoiYnVzaW5lc3MxQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0JVU0lORVNTIiwiaWF0IjoxNzMzNjQ2OTAyLCJleHAiOjE3MzM2NDc4MDJ9.z4Q9uYtJ_m5UyHr6GVrSriEbGA2rTZ_s7_Mzw_t146o
Accept: text/event-stream

### 멤버 구독

GET http://localhost:8080/api/subscribe/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoiZXh0cmExQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJpYXQiOjE3MzM1NzY5OTEsImV4cCI6MTczMzU3Nzg5MX0.7_ySUZ0piLzYMy6R43pwcA0x4b2nPbl_h-49DmNSmfg
Accept: text/event-stream

### 예약등록

POST http://localhost:8080/api/v1/reservations/9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoiZXh0cmExQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJpYXQiOjE3MzM2NDMwNTgsImV4cCI6MTczMzY0Mzk1OH0.D85pBlmy5aErPgtFJD3Ujm0MTmX7TU5yOhNdFjTLdHw

{
  "reservationName": "홍길동",
  "reservationPhoneNumber": "010-0000-0000",
  "capacity" : 4,
  "price" : 12000,
  "startTime": "2024-12-02T19:00:00",
  "endTime": "2024-12-02T20:59:00"
}
### 결제
POST http://localhost:8080//api/v1/payments/toss?reservationId=24
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoiZXh0cmExQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJpYXQiOjE3MzM2NDMwNTgsImV4cCI6MTczMzY0Mzk1OH0.D85pBlmy5aErPgtFJD3Ujm0MTmX7TU5yOhNdFjTLdHw

{
  "orderId": "string",
  "orderName": "ABC 스터디룸 ROOM A 예약",
  "totalAmount": 12000,
  "memberName": "홍길동12",
  "memberPhoneNum": "010-0000-0000",
  "tossPaymentMethod": "CARD"
}

### 결제 성공
POST http://localhost:8080//api/v1/payments/toss/success?reservationId=24
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoiZXh0cmExQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJpYXQiOjE3MzM2NDMwNTgsImV4cCI6MTczMzY0Mzk1OH0.D85pBlmy5aErPgtFJD3Ujm0MTmX7TU5yOhNdFjTLdHw

{
  "orderId": "string",
  "orderName": "ABC 스터디룸 ROOM A 예약",
  "totalAmount": 12000,
  "memberName": "홍길동12",
  "memberPhoneNum": "010-0000-0000",
  "tossPaymentMethod": "CARD"
}
### 알람조회
GET  http://localhost:8080/api/v1/sub/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoiYnVzaW5lc3M0QGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0JVU0lORVNTIiwiaWF0IjoxNzMzNjM5MTM5LCJleHAiOjE3MzM2NDAwMzl9.KFCyMW1YD4SJIS2QvThB5Z2id5zRK7FiSzJQG4YUGd8


### 결제 알람조회
GET  http://localhost:8080/api/v1/subReservation/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoiYnVzaW5lc3M0QGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0JVU0lORVNTIiwiaWF0IjoxNzMzNjQ0MTc5LCJleHAiOjE3MzM2NDUwNzl9.YsWlVN-nDN60V2VYJoNgJ0idHIWw0ywriqQ_WH8B1MQ

### 사용자 알람조회
GET  http://localhost:8080/api/v1/subReservation/memberlist
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoiZXh0cmExQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJpYXQiOjE3MzM1NzY5OTEsImV4cCI6MTczMzU3Nzg5MX0.7_ySUZ0piLzYMy6R43pwcA0x4b2nPbl_h-49DmNSmfg


### 리뷰등록
POST http://localhost:8080/api/v1/review/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoiZXh0cmExQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJpYXQiOjE3MzM1NzQ5ODQsImV4cCI6MTczMzU3NTg4NH0.b1tLhrNFTAf6YnmagWMlRYPalMQFvSl4O24-vf9SUDU

{
    "reservationId" : 9,
    "workPlaceName" : "ENI스터디룸",
    "reviewContent": "좋습니다",
    "reviewRating" : 4
 }
### 멤버 회원가입
POST http://localhost:8080/api/v1/member/signup
Content-Type: application/json

{
    "nickName" : "테스트",
    "phoneNumber": "010-3333-2222",
    "sex" : "MALE",
    "email" : "123@aa.com",
    "pwd" : "Tpgur8597!!",
    "birthDay" : "2024-01-01"
}
### 멤버 로그인
POST http://localhost:8080/login/member
Content-Type: application/json

{

  "email" : "extra1@gmail.com",
  "password" : "Test1234!"

}

### 예약 등록
POST http://localhost:8080/api/v1/reservations/12
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoibWVtYmVyNUBtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJpYXQiOjE3MzMzMTkxOTgsImV4cCI6MTczMzMyMDA5OH0.HpIkdS7MeuKbSRwPWrTGPm3CAMrd0ZhZdiH2NRVxI7M

{
  "reservationName": "홍길동",
  "reservationPhoneNumber": "010-0000-0000",
  "capacity" : 4,
  "price" : 12000,
  "startTime": "2024-12-03T13:00:00",
  "endTime": "2024-12-03T14:59:00"
}