POST http://localhost:8080/api/v1/business/signup
Content-Type: application/json

{
		"businessName":"사업자3",
		"businessEmail":"business1@email.com",
	     "businessPwd":"testT!123",
		"businessNum":"133-12-12345"
}

### 로그인
POST http://localhost:8080/login/business
Content-Type: application/json

{
  "email" : "business5@gmail.com",
  "password" : "Test1234!"

}
### 구독

GET http://localhost:8080/api/subscribe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoiYnVzaW5lc3M1QGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0JVU0lORVNTIiwiaWF0IjoxNzMzNTA5NzQ0LCJleHAiOjE3MzM1MTA2NDR9.mrLSE8iU2TiLpC15qHWZCGBoWWDVKBEDwjC8ar_k-Jw
Accept: text/event-stream

### 예약등록

POST http://localhost:8080/api/v1/reservations/1
Content-Type: application/json

{
  "reservationName": "홍길동",
  "reservationPhoneNumber": "010-0000-0000",
  "capacity" : 4,
  "price" : 12000,
  "startTime": "2024-12-03T13:00:00",
  "endTime": "2024-12-03T14:59:00"

}

### 알람조회
GET  http://localhost:8080/api/v1/sub/list?workplaceId=5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoiYnVzaW5lc3M1QGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0JVU0lORVNTIiwiaWF0IjoxNzMzNTEzMTc3LCJleHAiOjE3MzM1MTQwNzd9.GeTHlsYJR_PYVaHq8vjkfYsTFH0d0e_VaUTIztXweCg

### 리뷰등록
POST http://localhost:8080/api/v1/review/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoiZXh0cmExQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJpYXQiOjE3MzM1MDk3NTUsImV4cCI6MTczMzUxMDY1NX0.WyJpBZYPcNf_vtGlIts1LleRZ8e2Z8xOy-q8s04AkKg

{
    "reservationId" : 8,
    "workPlaceName" : "ENI스터디룸",
    "reviewContent": "좋습니다",
    "reviewRating" : 4
 }
### 멤버 회원가입
POST http://localhost:8080/api/v1/member/signup
Content-Type: application/json

{
    "nickName" : "테스트",
    "phoneNumber": "010-3333-2222",
    "sex" : "MALE",
    "email" : "123@aa.com",
    "pwd" : "Tpgur8597!!",
    "birthDay" : "2024-01-01"
}
### 멤버 로그인
POST http://localhost:8080/login/member
Content-Type: application/json

{

  "email" : "extra1@gmail.com",
  "password" : "Test1234!"

}

### 예약 등록
POST http://localhost:8080/api/v1/reservations/12
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsInVzZXJuYW1lIjoibWVtYmVyNUBtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJpYXQiOjE3MzMzMTkxOTgsImV4cCI6MTczMzMyMDA5OH0.HpIkdS7MeuKbSRwPWrTGPm3CAMrd0ZhZdiH2NRVxI7M

{
  "reservationName": "홍길동",
  "reservationPhoneNumber": "010-0000-0000",
  "capacity" : 4,
  "price" : 12000,
  "startTime": "2024-12-03T13:00:00",
  "endTime": "2024-12-03T14:59:00"
}